# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/demonkingswarn/dl/gitthings/rofi-file-browser-extended

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/demonkingswarn/dl/gitthings/rofi-file-browser-extended

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demonkingswarn/dl/gitthings/rofi-file-browser-extended/CMakeFiles /home/demonkingswarn/dl/gitthings/rofi-file-browser-extended//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demonkingswarn/dl/gitthings/rofi-file-browser-extended/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named filebrowser

# Build rule for target.
filebrowser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filebrowser
.PHONY : filebrowser

# fast build rule for target.
filebrowser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/build
.PHONY : filebrowser/fast

#=============================================================================
# Target rules for targets named manpage

# Build rule for target.
manpage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 manpage
.PHONY : manpage

# fast build rule for target.
manpage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/manpage.dir/build.make CMakeFiles/manpage.dir/build
.PHONY : manpage/fast

src/cmds.o: src/cmds.c.o
.PHONY : src/cmds.o

# target to build an object file
src/cmds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/cmds.c.o
.PHONY : src/cmds.c.o

src/cmds.i: src/cmds.c.i
.PHONY : src/cmds.i

# target to preprocess a source file
src/cmds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/cmds.c.i
.PHONY : src/cmds.c.i

src/cmds.s: src/cmds.c.s
.PHONY : src/cmds.s

# target to generate assembly for a file
src/cmds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/cmds.c.s
.PHONY : src/cmds.c.s

src/filebrowser.o: src/filebrowser.c.o
.PHONY : src/filebrowser.o

# target to build an object file
src/filebrowser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/filebrowser.c.o
.PHONY : src/filebrowser.c.o

src/filebrowser.i: src/filebrowser.c.i
.PHONY : src/filebrowser.i

# target to preprocess a source file
src/filebrowser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/filebrowser.c.i
.PHONY : src/filebrowser.c.i

src/filebrowser.s: src/filebrowser.c.s
.PHONY : src/filebrowser.s

# target to generate assembly for a file
src/filebrowser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/filebrowser.c.s
.PHONY : src/filebrowser.c.s

src/files.o: src/files.c.o
.PHONY : src/files.o

# target to build an object file
src/files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/files.c.o
.PHONY : src/files.c.o

src/files.i: src/files.c.i
.PHONY : src/files.i

# target to preprocess a source file
src/files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/files.c.i
.PHONY : src/files.c.i

src/files.s: src/files.c.s
.PHONY : src/files.s

# target to generate assembly for a file
src/files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/files.c.s
.PHONY : src/files.c.s

src/icons.o: src/icons.c.o
.PHONY : src/icons.o

# target to build an object file
src/icons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/icons.c.o
.PHONY : src/icons.c.o

src/icons.i: src/icons.c.i
.PHONY : src/icons.i

# target to preprocess a source file
src/icons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/icons.c.i
.PHONY : src/icons.c.i

src/icons.s: src/icons.c.s
.PHONY : src/icons.s

# target to generate assembly for a file
src/icons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/icons.c.s
.PHONY : src/icons.c.s

src/keys.o: src/keys.c.o
.PHONY : src/keys.o

# target to build an object file
src/keys.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/keys.c.o
.PHONY : src/keys.c.o

src/keys.i: src/keys.c.i
.PHONY : src/keys.i

# target to preprocess a source file
src/keys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/keys.c.i
.PHONY : src/keys.c.i

src/keys.s: src/keys.c.s
.PHONY : src/keys.s

# target to generate assembly for a file
src/keys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/keys.c.s
.PHONY : src/keys.c.s

src/options.o: src/options.c.o
.PHONY : src/options.o

# target to build an object file
src/options.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/options.c.o
.PHONY : src/options.c.o

src/options.i: src/options.c.i
.PHONY : src/options.i

# target to preprocess a source file
src/options.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/options.c.i
.PHONY : src/options.c.i

src/options.s: src/options.c.s
.PHONY : src/options.s

# target to generate assembly for a file
src/options.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/options.c.s
.PHONY : src/options.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filebrowser.dir/build.make CMakeFiles/filebrowser.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... manpage"
	@echo "... filebrowser"
	@echo "... src/cmds.o"
	@echo "... src/cmds.i"
	@echo "... src/cmds.s"
	@echo "... src/filebrowser.o"
	@echo "... src/filebrowser.i"
	@echo "... src/filebrowser.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/icons.o"
	@echo "... src/icons.i"
	@echo "... src/icons.s"
	@echo "... src/keys.o"
	@echo "... src/keys.i"
	@echo "... src/keys.s"
	@echo "... src/options.o"
	@echo "... src/options.i"
	@echo "... src/options.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

